server:
  port: 8031
spring:
  profiles:
    active: dev
    include:
      - api-config
  output:
    ansi:
      enabled: always
# 使用log4j2记录日志 默认日志名log4j2-spring.xml
#logging:
#    config: classpath:log4j2-spring.xml
#    level:
#        cn.tlh.*: info

