server:
  port: 8090
  # 使用IP无法访问应用 尝试添加tomcat启动参数  -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false
  # 设置你的访问ip
  # https://stackoverflow.com/questions/23946369/how-to-configure-embedded-tomcat-integrated-with-spring-to-listen-requests-to-ip
#  address: 0.0.0.0
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
# 使用log4j2记录日志
#logging:
#  config: classpath:log4j2-spring.xml
#  level:
#    cn.tlh.*: info
# log config
logging:
  config: classpath:logback.xml

